package jaya.jaramillo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClinicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicaAllPropertiesEquals(Clinica expected, Clinica actual) {
        assertClinicaAutoGeneratedPropertiesEquals(expected, actual);
        assertClinicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicaAllUpdatablePropertiesEquals(Clinica expected, Clinica actual) {
        assertClinicaUpdatableFieldsEquals(expected, actual);
        assertClinicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicaAutoGeneratedPropertiesEquals(Clinica expected, Clinica actual) {
        assertThat(expected)
            .as("Verify Clinica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicaUpdatableFieldsEquals(Clinica expected, Clinica actual) {
        assertThat(expected)
            .as("Verify Clinica relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getCorreo()).as("check correo").isEqualTo(actual.getCorreo()))
            .satisfies(e -> assertThat(e.getHorarioAtencion()).as("check horarioAtencion").isEqualTo(actual.getHorarioAtencion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicaUpdatableRelationshipsEquals(Clinica expected, Clinica actual) {
        // empty method
    }
}
