package jaya.jaramillo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoTerapiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoTerapiaAllPropertiesEquals(TipoTerapia expected, TipoTerapia actual) {
        assertTipoTerapiaAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoTerapiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoTerapiaAllUpdatablePropertiesEquals(TipoTerapia expected, TipoTerapia actual) {
        assertTipoTerapiaUpdatableFieldsEquals(expected, actual);
        assertTipoTerapiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoTerapiaAutoGeneratedPropertiesEquals(TipoTerapia expected, TipoTerapia actual) {
        assertThat(expected)
            .as("Verify TipoTerapia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoTerapiaUpdatableFieldsEquals(TipoTerapia expected, TipoTerapia actual) {
        assertThat(expected)
            .as("Verify TipoTerapia relevant properties")
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoTerapiaUpdatableRelationshipsEquals(TipoTerapia expected, TipoTerapia actual) {
        // empty method
    }
}
