name: Trigger auto deployment for agendamiento

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [master]
    paths:
      - '**'
      - '.github/workflows/agendamiento-AutoDeployTrigger-bc05f1df-70b6-49f5-9f1f-07e12f127e62.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AGENDAMIENTO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGENDAMIENTO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGENDAMIENTO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl:
          registryUsername: ${{ secrets.AGENDAMIENTO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AGENDAMIENTO_REGISTRY_PASSWORD }}
          containerAppName: agendamiento
          resourceGroup: recurso_agendamiento
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
